### PR TITLE
[WIP] Fix: #587. Bump node to 16

### PR DESCRIPTION
**Pull request by ioggstream**
## This PR

bump node 16

### CODE REVIEW

**Comment by emilioSp** [comment]
https://github.com/italia/api-oas-checker/pull/588/commits/f9f651d514a9106a1b5d445c45e98c0c6e111c8d
@ioggstream there is also the .nvmrc, for the ones who have node installed directly on their development machine.

**Comment by emilioSp** [comment]
https://github.com/italia/api-oas-checker/pull/588/commits/f9f651d514a9106a1b5d445c45e98c0c6e111c8d
@ioggstream there is also the .nvmrc, for the ones who have node installed directly on their development machine.

**Comment by ioggstream** [comment]
@LorenzoS92 @bfabio come mai non deploya su vercel? Non ho accesso ad oggi. Chi più fixare?

**Comment by LorenzoS92** [comment]
Non ho accessi su Vercel al momento. @bfabio puoi aiutarci te? Al rientro, vi chiederò gli accessi.

**Comment by bfabio** [comment]
@ioggstream we changed the log security setting on Vercel, as there is no private information there, so the logs are publicly visible now: https://vercel.com/dip-trasformazione-digitale/api-oas-checker/9Dm7QcBJ6Q3fQSJTprVATFeBYNH5

**Pull request merged**
