### PR TITLE
Fix: #455. Add a Test button.

### PR DESCRIPTION
**Pull request by ioggstream**
## This PR

- adds a "Test" button that loads the broken file "errorfile.yaml"
- show various kinds of errors

### CODE REVIEW

**Comment by bfabio** [comment]
I think the new button's purpose is not clear at first glance. What about grouping the template files with something like:

image

**Comment by ioggstream** [comment]
@bfabio I'm open to whatever @Fupete suggests :)

We need at least two new buttons:

- Reformat/Convert to yaml
- Showcase an errored file (useful to test new PRs via vercel)

**Comment by emilioSp** [comment]
> 
I agree with you. `Test` is not understandable. I like your solution @bfabio 

BTW, the easiest solution (not the best) is 
- rename the button `template` in `example` 
- rename `test` in `example with errors`

...or something similar

**Comment by ioggstream** [comment]
Eccolo qui... avete suggerimenti? @bfabio 

image

**Review by emilioSp — APPROVED** [review]

**Review by ioggstream — COMMENTED** [review]
LGTM

**Review by bfabio — APPROVED** [review]

**Pull request merged**
