### PR TITLE
Fix: #10. Format file as yaml.

### PR DESCRIPTION
**Pull request by ioggstream**
## This PR

- reformats (json only for now) the editor content

### CODE REVIEW

**Comment by ioggstream** [comment]
@dependabot rebase

**Comment by ioggstream** [comment]
@github rebase

**Comment by bfabio** [comment]
I think this would be better served as an editor command.

Monaco is pretty powerful and it should be able to do it by itself, in a more natural way for the user, along with all other editor-centric features (F1 or right click bring up the commands palette), I'm not sure why formatting is not already there, maybe it must be explicitly configured to do it.

**Comment by ioggstream** [comment]
@bfabio could you provide a draft PR based on Monaco? Thx++, R.

**Comment by bfabio** [comment]
@ioggstream Something like #507

**Comment by ioggstream** [comment]
moved to #512

**Pull request closed without merging**
